Ко второму РК
java-park-mail-ru/pirates-02-2017 pull request #2
Opened 2017-03-27 23:11 UTC by vileven

Все требования выполнены. 
Мы делаем с помощью ORM(Чистые sql запросы у нас и так в курсе БД, нам захотелось что-то другое). Также мы добавили миграции с помощью Flywaydb.
Единственное, код будет немного вылизываться до четверга(нужно удалить не используемые классы, почистить комментарии и т.д.).

2017-03-27 23:16 UTC, vileven commented
прошу простить за мою вакханалию из 10 коммитов с просьбами запуститься на хероку. Я упорно искал проблему в коде. А оказалось ошибка в том, что heroku не создала в репозитории базу данных, и конечно поэтому не приходили нужные переменные окружения... Все решилось командой: 
`heroku addons:create heroku-postgresql:hobby-dev --app motion-project
`

2017-03-28 09:28 UTC, KSolovyev commented
уберите закомментированный код, пожалуйста

2017-03-28 21:27 UTC, 8coon commented
Мы вроде всё подчистили, можете проверять код

2017-03-29 06:00 UTC, KSolovyev requested changes
Еще не все

2017-03-29 06:00 UTC, KSolovyev commented on pom.xml
> +        <!--</dependency>-->
здесь тоже надо почистить. Вообще с системами контроля версий и ide, которая хранит все ваши изменения, держать закоментированный код - бессмысленно

2017-03-29 06:00 UTC, KSolovyev commented on src/main/java/api/DAO/DAO.java
> +public interface DAO<T extends Model<ID>, ID extends Serializable> {
комментарии надо убрать. Они у вас здесь ничего не поясняют, просто размер файла увеличивают

2017-03-29 06:00 UTC, KSolovyev commented on src/main/java/api/repository/UserRepository.java
> +    // T findUsersByLoginOrByEmail(@NotNull String login, @NotNull String email);
уберите

2017-03-29 06:00 UTC, KSolovyev commented on src/main/java/api/services/AccountService.java
> +public class AccountService extends AbstractService {
нужно избегать названий с Abstract. AbstractService, AbstractEntity, AbstractData - это вообще ничего не говорит о том, что находится внутри класса

2017-03-29 06:07 UTC, vileven commented on src/main/java/api/services/AccountService.java
> +public class AccountService extends AbstractService {
Как в таком случае стоит назвать базовый сервис от которого все остальные наследуются?

2017-03-29 06:07 UTC, vileven commented on src/main/java/api/services/AccountService.java
> +public class AccountService extends AbstractService {
BaseService?

2017-03-29 08:15 UTC, KSolovyev commented on src/main/java/api/services/AccountService.java
> +public class AccountService extends AbstractService {
Это название тоже ничего не говорит)
И у вас только AccountService от него наследуется. Предлагаю вообще его убрать и все добавить в AccountService

2017-03-29 15:49 UTC, vileven commented
сделали

2017-03-29 19:42 UTC, KSolovyev requested changes

2017-03-29 19:42 UTC, KSolovyev commented on src/main/java/api/DAO/DAO.java
> +public interface DAO<T extends Model<ID>, ID extends Serializable> {
done

2017-03-29 19:42 UTC, KSolovyev commented on src/main/java/api/controllers/GameController.java
> +    @PostMapping("/scores")
а почему post?

2017-03-29 19:42 UTC, KSolovyev commented on src/main/java/api/model/Model.java
> +public abstract class Model<ID extends Serializable> {
давайте параметр шаблона назовем одной буквой. И почему он Serializable?

2017-03-29 19:42 UTC, KSolovyev commented on src/main/java/api/validators/EmailValidator.java
> +        if (!value.matches("^[a-zA-Z0-9_.-]+@[a-zA-Z0-9_.-]+\\.[a-zA-Z0-9_]+$")) {
не надо почту проверять регуляркой. Лучшее, что вы можете сделать - это посмотреть, что есть что-то до, что есть что-то после и послать туда письмо для подтверждения

2017-03-29 19:47 UTC, KSolovyev commented on src/main/java/api/controllers/ValidatorController.java
> +public class ValidatorController extends ApplicationController {
выглядит как задача фронтовой валидации. Для серверной обычно хватает Spring validation. Там написаны аннотации для модели, типа `@Size` , `@RegExp`, которые отклоняют неподходящие запросы. А юзабилити уже на фронте реализуется

2017-03-29 19:53 UTC, vileven commented on src/main/java/api/controllers/ValidatorController.java
> +public class ValidatorController extends ApplicationController {
У нас просто фронт асинхронно обращается к серверу когда пользователь вводит данные регистрации, соответсвенно, нам, как минимум, надо проверять на уникальность логина и емайла. Кажется, что в таком случае можно и остальную логику вынести сюда(благо она там элементарная). Вот посмотрите как это работает.
https://project-motion.herokuapp.com/

2017-03-29 20:00 UTC, vileven commented on src/main/java/api/model/Model.java
> +public abstract class Model<ID extends Serializable> {
Переименуем в Identificator, на счет Serializable, мы в HttpSession передаем идентификатор (USER_ID), ведь в теории идентификатором может быть что угодно... Я явно декларировать то, что id должен реализовывать интерфейс, чтобы в контроллере гарантированно не было проблем...

2017-03-29 21:16 UTC, KSolovyev commented on src/main/java/api/controllers/ValidatorController.java
> +public class ValidatorController extends ApplicationController {
да я понял, как работает. Фронт просто спамит вас запросами)

2017-03-30 11:11 UTC, 8coon commented
Я поставил ToDo в GameController на изменение метода, мы когда будем переделывать фронт, этот метод тоже поменяем и добавим в документацию. Ещё переименовал ID в K в модели и вообще везде, где оно было. Убрал регулярку из валидации email, теперь оно просто смотрит, чтобы в строке был символ "@".

2017-04-09 21:38 UTC, merged